services:

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun

    cap_add:
      - NET_ADMIN

    restart: unless-stopped

    ports:
      - "8888:8888"

    volumes:
      - ${CONFIG_ROOT}/gluetun:/gluetun

    environment:
      - TZ=${TZ}

networks:
  default:
    name: kingypinas
